require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KlassTestsController do

  # This should return the minimal set of attributes required to create a valid
  # KlassTest. As you add validations to KlassTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "klass" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KlassTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all klass_tests as @klass_tests" do
      klass_test = KlassTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:klass_tests).should eq([klass_test])
    end
  end

  describe "GET show" do
    it "assigns the requested klass_test as @klass_test" do
      klass_test = KlassTest.create! valid_attributes
      get :show, {:id => klass_test.to_param}, valid_session
      assigns(:klass_test).should eq(klass_test)
    end
  end

  describe "GET new" do
    it "assigns a new klass_test as @klass_test" do
      get :new, {}, valid_session
      assigns(:klass_test).should be_a_new(KlassTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested klass_test as @klass_test" do
      klass_test = KlassTest.create! valid_attributes
      get :edit, {:id => klass_test.to_param}, valid_session
      assigns(:klass_test).should eq(klass_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KlassTest" do
        expect {
          post :create, {:klass_test => valid_attributes}, valid_session
        }.to change(KlassTest, :count).by(1)
      end

      it "assigns a newly created klass_test as @klass_test" do
        post :create, {:klass_test => valid_attributes}, valid_session
        assigns(:klass_test).should be_a(KlassTest)
        assigns(:klass_test).should be_persisted
      end

      it "redirects to the created klass_test" do
        post :create, {:klass_test => valid_attributes}, valid_session
        response.should redirect_to(KlassTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved klass_test as @klass_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        KlassTest.any_instance.stub(:save).and_return(false)
        post :create, {:klass_test => { "klass" => "invalid value" }}, valid_session
        assigns(:klass_test).should be_a_new(KlassTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KlassTest.any_instance.stub(:save).and_return(false)
        post :create, {:klass_test => { "klass" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested klass_test" do
        klass_test = KlassTest.create! valid_attributes
        # Assuming there are no other klass_tests in the database, this
        # specifies that the KlassTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KlassTest.any_instance.should_receive(:update).with({ "klass" => "" })
        put :update, {:id => klass_test.to_param, :klass_test => { "klass" => "" }}, valid_session
      end

      it "assigns the requested klass_test as @klass_test" do
        klass_test = KlassTest.create! valid_attributes
        put :update, {:id => klass_test.to_param, :klass_test => valid_attributes}, valid_session
        assigns(:klass_test).should eq(klass_test)
      end

      it "redirects to the klass_test" do
        klass_test = KlassTest.create! valid_attributes
        put :update, {:id => klass_test.to_param, :klass_test => valid_attributes}, valid_session
        response.should redirect_to(klass_test)
      end
    end

    describe "with invalid params" do
      it "assigns the klass_test as @klass_test" do
        klass_test = KlassTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KlassTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => klass_test.to_param, :klass_test => { "klass" => "invalid value" }}, valid_session
        assigns(:klass_test).should eq(klass_test)
      end

      it "re-renders the 'edit' template" do
        klass_test = KlassTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KlassTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => klass_test.to_param, :klass_test => { "klass" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested klass_test" do
      klass_test = KlassTest.create! valid_attributes
      expect {
        delete :destroy, {:id => klass_test.to_param}, valid_session
      }.to change(KlassTest, :count).by(-1)
    end

    it "redirects to the klass_tests list" do
      klass_test = KlassTest.create! valid_attributes
      delete :destroy, {:id => klass_test.to_param}, valid_session
      response.should redirect_to(klass_tests_url)
    end
  end

end
